### ISSUE TITLE
issue with using in browser

### ISSUE THREAD

**Issue by sekur** [commenthol/debug-level#14]
There is a problem with last line in how we are exporting in `src/browser.js`.

It should be `export default Log;` instead of `module.exports = Log`

The issue started with version `2.0.2` and is still present in `latest`

**Comment by sekur** [comment]
Another option is to update the `package.json` for `browser:` to point to `lib/browser.js` instead of `src/browser.js`.

**Comment by commenthol** [comment]
@sekur Thanks for rising. I prefer to do a proper ES5 export as modern browser tend to prefer this. 
A PR is in the making which will fix this issue.

**Comment by commenthol** [comment]
v2.1.2 is published.
