### ISSUE TITLE
Is it possible to dynamically turn on/off separate namespaces without overriding all previous namespace settings?

### ISSUE THREAD

**Issue by gunhaxxor** [commenthol/debug-level#20]
I think the original debug package "writes back" to the DEBUG env var which i guess in theory would allow a way to individually turn on/off namespaces by doing something like:
```
debug.enable('AddedNameSpace*' + process.env.DEBUG);
```

Is there some way to achieve individual on/off for namespaces with debug-level? Would be great 😊

**Comment by commenthol** [comment]
From the README:

Log "server" at level INFO, and all other modules at level ERROR
```
$ DEBUG=INFO:server,ERROR:* node examples/server.js
```

or in your script (using the sample from above)
```js
Log.options({namespaces: 'INFO:server,ERROR:*'})
```

Any change won't have any effect until the script is restarted.
I'm not sure if this is the thing you were looking for?

**Comment by gunhaxxor** [comment]
My aim was to be able to turn on (or off) a single namespace without affecting the settings for any other namespace. This in a context where I don't know the other namespaces currently in use. 

I ended up with something like this:
```
//file:  Client.ts
import { Log } from 'debug-level';

const log = new Log('Client');

// comment or uncomment the following line to toggle the Client namespace
process.env.DEBUG = 'Client*, ' + process.env.DEBUG;
log.enable(process.env.DEBUG);

```
By reading the the ENV variable and writing back to it, I can use this pattern in several files without worrying that one file/module overwrites the namespace set by another file. Seems to work fine 😃
