### ISSUE TITLE
Implicit DEBUG_LEVEL?

### ISSUE THREAD

**Issue by mraistrick** [commenthol/debug-level#25]
If I clone the repo & npm install followed by `$ node examples/levels.js` i.e. neither DEBUG or DEBUG_LEVEL set either in the command or in the environment:

$ printenv | grep DEBUG
$

I see the following output - but according to the documentation should only see the LOG level:

  TRACE test {
  TRACE test   "trace": "it"
  TRACE test } +0ms
  DEBUG test {
  DEBUG test   "object": 1
  DEBUG test } +2ms
  INFO test hello world +1ms
  WARN test huh {
  WARN test   "ghost": "rider"
  WARN test } +0ms
  ERROR test boom {
  ERROR test   "err": {
  ERROR test     "msg": "boom",
  ERROR test     "name": "Error",
  ERROR test     "stack": "Error: boom
  ERROR test     at file:///home/mike/log-level-test/debug-level/examples/levels.js:11:11
  ERROR test     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
  ERROR test     at async Promise.all (index 0)
  ERROR test     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
  ERROR test     at async loadESM (node:internal/process/esm_loader:91:5)
  ERROR test     at async handleMainPromise (node:internal/modules/run_main:65:12)"
  ERROR test   }
  ERROR test } +0ms
  FATAL test fatal test +1ms
  LOG test always logs +1ms
  DEBUG log:A {
  DEBUG log:A   "object": 1
  DEBUG log:A } +0ms
  INFO log:A hello world +1ms
  WARN log:A huh {
  WARN log:A   "ghost": "rider"
  WARN log:A } +0ms
  ERROR log:A baam {
  ERROR log:A   "err": {
  ERROR log:A     "msg": "baam",
  ERROR log:A     "name": "Error",
  ERROR log:A     "stack": "Error: baam
  ERROR log:A     at file:///home/mike/log-level-test/debug-level/examples/levels.js:20:12
  ERROR log:A     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
  ERROR log:A     at async Promise.all (index 0)
  ERROR log:A     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
  ERROR log:A     at async loadESM (node:internal/process/esm_loader:91:5)
  ERROR log:A     at async handleMainPromise (node:internal/modules/run_main:65:12)"
  ERROR log:A   }
  ERROR log:A } +0ms
  FATAL log:A fatal A +1ms
  DEBUG log:B {
  DEBUG log:B   "object": 1
  DEBUG log:B } +0ms
  INFO log:B hello world +1ms
  WARN log:B huh {
  WARN log:B   "ghost": "rider"
  WARN log:B } +0ms
  ERROR log:B bbbm {
  ERROR log:B   "err": {
  ERROR log:B     "msg": "bbbm",
  ERROR log:B     "name": "Error",
  ERROR log:B     "stack": "Error: bbbm
  ERROR log:B     at file:///home/mike/log-level-test/debug-level/examples/levels.js:28:12
  ERROR log:B     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
  ERROR log:B     at async Promise.all (index 0)
  ERROR log:B     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
  ERROR log:B     at async loadESM (node:internal/process/esm_loader:91:5)
  ERROR log:B     at async handleMainPromise (node:internal/modules/run_main:65:12)"
  ERROR log:B   }
  ERROR log:B } +0ms
  FATAL log:B fatal B +0ms

What am I missing?

**Comment by commenthol** [comment]
Hi @mraistrick,
examples/levels.js has the trace level option set in line 4
```js
Log.options({ level: 'trace' }) // call options before your instances
```
Please set to any level you'd like to log.
Btw. this would only log FATAL 
```sh
DEBUG_LEVEL=FATAL node examples/levels.js
```
or even more fine granular
```sh
DEBUG=FATAL:*,WARN:log:B node examples/levels.js 
```
See full options in README
