### ISSUE TITLE
Compact/tiny mode 

### ISSUE THREAD

**Issue by isuvorov** [commenthol/debug-level#4]
Would you like to make compact/tiny mode for log levels.

Something like this:
`DEBUG` => `[d]`
`INFO` => `[i]`
`ERROR` => `[r]`

I could do the PR.

**Comment by commenthol** [comment]
Hi @isuvorov, is this related to the output? Could you explain where this mode would be applied?

**Comment by commenthol** [comment]
v2.0.0 adds numbered levels which can be enabled with option `levelNumbers` or env var DEBUG_LEVEL_NUMBERS.
Maybe this is an option for you.
