### ISSUE TITLE
diff with debug-levels ?

### ISSUE THREAD

**Issue by dcsan** [commenthol/debug-level#5]
just wondering what are differences with similar named:

https://github.com/tilleps/debug-levels

eg that wraps TJs `debug` module, is this project written from ground up?

any major differences?

**Comment by commenthol** [comment]
Hi @dcsan, 

This project uses concepts from debug and bunyan. It borrowed some code from debug (Namespaces.js) but all the rest was written from ground up. 

Its primary purpose is to allow developers to use colored and human readable debug output like `debug` during development. Whereas for production it uses a pure and strict [NDJSON](http://ndjson.org/) output for later processing e.g. with ELK stack.

It has some gotchas like logging from SPA using an express middleware, custom streams, custom formatters, ... 
Details are in the README.
