### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by YPetremann** [commenthol/debug-level#6]
Actually colors seems to follow a hardcoded list of colors, in some case they can be hard to read.
Two solutions to solve this problem :
- declaring a color during instanciation:
```
const Log = require('debug-level')('server','#FF0000');
```

- exposing colors list in options to let people add and remove colors:
invalid colors or no color available ? use white by default

**Comment by commenthol** [comment]
@YPetremann Could you please tell me the situation which you'd consider as "improvable" here? 
E.g. white background in 16 color TTY  with yellow text. I personally would like to provide a more generic approach where a developer does not need to attribute colors which only suits its own dev environment.

**Comment by YPetremann** [comment]
const Log = require('debug-level')('server');
    Log.log(`Server listening at http://localhost:80`)

In this occurrence it use #3300CC on #000000 background, which is pretty dark.

**Comment by commenthol** [comment]
@YPetremann I tried to remove the low contrast colors in PR #7. Maybe this fixes your problem and custom colors are not required any longer? What do you think?

**Comment by commenthol** [comment]
v1.0.0 is published

**Comment by airstrike** [comment]
customizing colors would be nice indeed

my biggest issue is I have a ton of different modules, each with their own logger, and given the random nature of colors, depending on the luck of the draw, sometimes you can get too similar colors for different modules, defeating the purpose of having colors to begin with.

also some of the colors are quite jarring like the bright green or bright red, which stand out *more* than the colors used for the debug levels
